importer:
  log_level: info
  overwrite: true
  dry_run: false # true to skip actual update

raar:
  url: https://archiv.rabe.ch/api
  username:
  password:
  options:
    verify_ssl: 0 # OpenSSL::SSL::VERIFY_NONE

scraper:
  endpoint: https://data.rabe.ch/items/programs
